# Form implementation generated from reading ui file 'ScreenRecorder.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScreenRecorder(object):
    def setupUi(self, ScreenRecorder):
        ScreenRecorder.setObjectName("ScreenRecorder")
        ScreenRecorder.resize(450, 460)
        self.display_area = QtWidgets.QLabel(parent=ScreenRecorder)
        self.display_area.setGeometry(QtCore.QRect(70, 20, 320, 256))
        self.display_area.setStyleSheet("background-color: rgb(80,80,80);")
        self.display_area.setText("")
        self.display_area.setObjectName("display_area")
        self.background = QtWidgets.QListView(parent=ScreenRecorder)
        self.background.setGeometry(QtCore.QRect(0, 0, 451, 471))
        self.background.setStyleSheet("background-color: #0B192C;")
        self.background.setObjectName("background")
        self.line = QtWidgets.QFrame(parent=ScreenRecorder)
        self.line.setGeometry(QtCore.QRect(0, 290, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.connect_btn = QtWidgets.QPushButton(parent=ScreenRecorder)
        self.connect_btn.setGeometry(QtCore.QRect(70, 320, 161, 24))
        self.connect_btn.setObjectName("connect_btn")
        self.share_screen = QtWidgets.QPushButton(parent=ScreenRecorder)
        self.share_screen.setGeometry(QtCore.QRect(70, 360, 321, 24))
        self.share_screen.setObjectName("share_screen")
        self.other_settings = QtWidgets.QPushButton(parent=ScreenRecorder)
        self.other_settings.setGeometry(QtCore.QRect(70, 400, 321, 24))
        self.other_settings.setObjectName("other_settings")
        self.label_fps = QtWidgets.QLabel(parent=ScreenRecorder)
        self.label_fps.setGeometry(QtCore.QRect(10, 430, 54, 16))
        self.label_fps.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_fps.setObjectName("label_fps")
        self.index_fps = QtWidgets.QLabel(parent=ScreenRecorder)
        self.index_fps.setGeometry(QtCore.QRect(40, 430, 54, 16))
        self.index_fps.setStyleSheet("color: rgb(255, 255, 255);")
        self.index_fps.setObjectName("index_fps")
        self.cb_1 = QtWidgets.QCheckBox(parent=ScreenRecorder)
        self.cb_1.setGeometry(QtCore.QRect(380, 430, 79, 20))
        self.cb_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.cb_1.setObjectName("cb_1")
        self.label = QtWidgets.QLabel(parent=ScreenRecorder)
        self.label.setGeometry(QtCore.QRect(190, 430, 81, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=ScreenRecorder)
        self.lineEdit.setGeometry(QtCore.QRect(240, 320, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.background.raise_()
        self.display_area.raise_()
        self.line.raise_()
        self.connect_btn.raise_()
        self.share_screen.raise_()
        self.other_settings.raise_()
        self.label_fps.raise_()
        self.index_fps.raise_()
        self.cb_1.raise_()
        self.label.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(ScreenRecorder)
        QtCore.QMetaObject.connectSlotsByName(ScreenRecorder)

    def retranslateUi(self, ScreenRecorder):
        _translate = QtCore.QCoreApplication.translate
        ScreenRecorder.setWindowTitle(_translate("ScreenRecorder", "Form"))
        self.connect_btn.setText(_translate("ScreenRecorder", "连接设备"))
        self.share_screen.setText(_translate("ScreenRecorder", "开始投屏"))
        self.other_settings.setText(_translate("ScreenRecorder", "取消投屏"))
        self.label_fps.setText(_translate("ScreenRecorder", "fps :  "))
        self.index_fps.setText(_translate("ScreenRecorder", "None"))
        self.cb_1.setText(_translate("ScreenRecorder", "二值化"))
        self.label.setText(_translate("ScreenRecorder", "Server.Version"))
        self.lineEdit.setPlaceholderText(_translate("ScreenRecorder", "Port:"))
